services:
  - type: web
    name: rice-classifier-app
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    branch: main
   envVars:
  - key: PYTHON_VERSION
    value: 3.11

